<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/functions.php';

requireAuth();

$taskId = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$format = isset($_GET['format']) ? $_GET['format'] : 'md';
if ($format !== 'md' && $format !== 'docx') {
    http_response_code(400);
    exit('Formato no soportado');
}

$task = Database::fetchOne(
    'SELECT id, status, result_text, input_data, executed_by, created_at, completed_at
     FROM tasks WHERE id = ? AND task_type = ?',
    [$taskId, 'cve_search']
);

if (!$task || $task['status'] !== 'completed') {
    http_response_code(404);
    exit('Tarea no disponible');
}

$input = json_decode($task['input_data'] ?: '{}', true);
if (!is_array($input)) $input = [];
$cveId = isset($input['cve_id']) ? $input['cve_id'] : ('task-' . $taskId);
$body  = trim((string)(isset($task['result_text']) ? $task['result_text'] : ''));

$lang = isset($input['language']) ? strtolower((string)$input['language']) : 'es';
if ($lang !== 'es' && $lang !== 'en') $lang = 'es';

$safeName = preg_replace('/[^A-Za-z0-9_\-]/', '_', $cveId);

header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

// MARKDOWN
if ($format === 'md') {
    if ($lang === 'en') {
        $header = "# CVE Report — {$cveId}\n\n";
        $header .= "- **Task:** #{$task['id']}\n";
        $header .= "- **Created:** {$task['created_at']}\n";
        $header .= "- **Completed:** " . ($task['completed_at'] ?: '—') . "\n";
        $header .= "- **Executor:** " . ($task['executed_by'] ?: '—') . "\n\n---\n\n";
    } else {
        $header = "# Informe CVE — {$cveId}\n\n";
        $header .= "- **Tarea:** #{$task['id']}\n";
        $header .= "- **Creada:** {$task['created_at']}\n";
        $header .= "- **Completada:** " . ($task['completed_at'] ?: '—') . "\n";
        $header .= "- **Ejecutor:** " . ($task['executed_by'] ?: '—') . "\n\n---\n\n";
    }
    header('Content-Type: text/markdown; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $safeName . '.md"');
    echo $header . $body . "\n";
    exit;
}

// WORD — genera .doc (HTML) compatible con todos los hostings
$title = ($lang === 'en') ? 'CVE Technical Report' : 'Informe Técnico CVE';
$generated = ($lang === 'en') ? 'Generated by OrinSec' : 'Generado por OrinSec';
$taskLabel = ($lang === 'en') ? 'Task' : 'Tarea';
$dateLabel = ($lang === 'en') ? 'Date' : 'Fecha';

$html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">';
$html .= '<head><meta charset="utf-8"><title>' . htmlspecialchars($cveId) . '</title>';
$html .= '<style>';
$html .= 'body{font-family:Calibri,sans-serif;font-size:11pt;color:#333;margin:40px;line-height:1.5;}';
$html .= 'h1{font-family:"Calibri Light",sans-serif;font-size:28pt;color:#1F3864;text-align:center;margin-bottom:10px;}';
$html .= '.cveid{font-family:"Calibri Light",sans-serif;font-size:36pt;color:#C00000;text-align:center;font-weight:bold;margin:20px 0;}';
$html .= '.meta{text-align:center;color:#666;font-size:10pt;margin-bottom:30px;}';
$html .= 'hr{border:none;border-top:3px solid #2E74B5;margin:30px 0;}';
$html .= 'h2{font-family:"Calibri Light",sans-serif;font-size:16pt;color:#2E74B5;margin-top:24px;margin-bottom:8px;border-bottom:1px solid #ddd;padding-bottom:4px;}';
$html .= 'table{width:100%;border-collapse:collapse;margin:10px 0;font-size:10pt;}';
$html .= 'td,th{border:1px solid #bfbfbf;padding:6px 10px;}';
$html .= 'th{background:#2E74B5;color:#fff;font-weight:bold;text-align:left;}';
$html .= '.quote{margin:10px 0;padding:12px 20px;background:#f5f5f5;border-left:4px solid #999;font-style:italic;color:#555;}';
$html .= 'a{color:#0563C1;text-decoration:underline;}';
$html .= '.footer{text-align:center;color:#999;font-size:9pt;margin-top:40px;border-top:1px solid #bfbfbf;padding-top:10px;}';
$html .= '</style></head><body>';

$html .= '<h1>' . htmlspecialchars($title) . '</h1>';
$html .= '<div class="cveid">' . htmlspecialchars($cveId) . '</div>';
$html .= '<div class="meta">' . htmlspecialchars($taskLabel) . ': #' . htmlspecialchars((string)$task['id']) . ' &nbsp;|&nbsp; ' . htmlspecialchars($dateLabel) . ': ' . htmlspecialchars((string)$task['created_at']) . '</div>';
$html .= '<hr>';

// Parsear secciones del reporte (robusto: no depende de caracteres Unicode exactos)
$sections = [];
$current = '';
$content = [];
$lines = explode("\n", str_replace("\r", "", $body));
foreach ($lines as $line) {
    $line = rtrim($line);
    if ($line === '') continue;
    
    // Detectar titulo de seccion: cualquier linea con [ ... ]
    if (preg_match('/\[\s*([^\]]+)\s*\]/u', $line, $m)) {
        if ($current && $content) $sections[] = ['title' => $current, 'lines' => $content];
        $current = trim($m[1]);
        $content = [];
        continue;
    }
    
    // Ignorar lineas puras de borde/decoration (solo caracteres graficos + espacios)
    if (preg_match('/^[\x{2500}-\x{257F}\x{2550}-\x{256C}\s]+$/u', $line)) continue;
    
    // Quitar prefijos comunes de lista/borde: |, +, -, *, espacios, tabs
    $clean = preg_replace('/^[\s│┃┆┇┊┋├┤┌┐└┘┬┴┼┿╂╋┠┨┯┷┠┨├┤┼\-\*•►▸→⇒]+/u', '', $line);
    if ($clean !== '') $content[] = $clean;
}
if ($current && $content) $sections[] = ['title' => $current, 'lines' => $content];
// Si no se detectaron secciones, poner todo el body como una sola seccion
if (empty($sections) && $body !== '') {
    $sections[] = ['title' => 'Contenido', 'lines' => explode("\n", str_replace("\r", "", $body))];
}

foreach ($sections as $sec) {
    $secTitle = preg_replace('/[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{1F1E0}-\x{1F1FF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}]/u', '', $sec['title']);
    $secTitle = trim($secTitle);
    $html .= '<h2>' . htmlspecialchars($secTitle) . '</h2>';

    $isTable = true;
    $rows = [];
    foreach ($sec['lines'] as $ln) {
        if (preg_match('/^([^:]+):\s*(.+)$/u', $ln, $m)) {
            $rows[] = ['label' => trim($m[1]), 'value' => trim($m[2])];
        } else {
            $isTable = false;
            break;
        }
    }

    if ($isTable && count($rows) >= 2) {
        $html .= '<table>';
        $first = true;
        foreach ($rows as $r) {
            $html .= '<tr>';
            if ($first) {
                $html .= '<th>' . htmlspecialchars($r['label']) . '</th>';
                $html .= '<th>' . htmlspecialchars($r['value']) . '</th>';
                $first = false;
            } else {
                $html .= '<td>' . htmlspecialchars($r['label']) . '</td>';
                $html .= '<td>' . htmlspecialchars($r['value']) . '</td>';
            }
            $html .= '</tr>';
        }
        $html .= '</table>';
    } else {
        $isAnalysis = (stripos($secTitle, 'Risk Assessment') !== false || stripos($secTitle, 'Análisis') !== false);
        if ($isAnalysis && count($sec['lines']) > 0) {
            $html .= '<div class="quote">';
            foreach ($sec['lines'] as $ln) {
                $ln = preg_replace('/[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{1F1E0}-\x{1F1FF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}]/u', '', $ln);
                $html .= '<p>' . htmlspecialchars($ln) . '</p>';
            }
            $html .= '</div>';
        } else {
            foreach ($sec['lines'] as $ln) {
                $ln = preg_replace('/[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{1F1E0}-\x{1F1FF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}]/u', '', $ln);
                $html .= '<p>' . htmlspecialchars($ln) . '</p>';
            }
        }
    }
}

$html .= '<div class="footer">' . htmlspecialchars($generated) . ' — OrinSec Cyber Intelligence</div>';
$html .= '</body></html>';

header('Content-Type: application/msword');
header('Content-Disposition: attachment; filename="' . $safeName . '.doc"');
echo $html;
exit;
